apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: nextcloud
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    requirepass password
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfilename "appendonly.aof"
    protected-mode no
    dir /data
    save 900 1
    save 300 10
    save 60 10000
    # 性能优化
    stop-writes-on-bgsave-error no
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
